version: '3'

services:
  db:
    image: postgres
    container_name: pg-tanul
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "tanul1337"
      POSTGRES_USER: "tanul"
      POSTGRES_DB: "tanul"
    ports:
      - "5433:5432"

  adminer_container:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - 8082:8080

networks:
  adminer:
volumes:
  pg-data:
